# Site Info
title:              "Victor Alessander"
description:        "Software Engineer"
author_name:        "Victor Alessander" # change this to your name
logo_url:           https://avatars0.githubusercontent.com/u/21283066?v=4 # Get it from GitHub API: https://api.github.com/users/<username>

# facebook: VictorAlessander.xD
# twitter: mytwitter
# google: mygoogle
# instagram: victoralessander
# pinterest: mypinterest
linkedin: VictorAlessander
# youtube: myyoutube
spotify: v.a.g.r
github: VictorAlessander
# gitlab: mygitlab
# lastfm: mylastfm
stackoverflow: 7799765/victor-alessander
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd
email: alessander@protonmail.com

# Site Settings
url: https://victoralessander.github.io # main url
# baseurl:            /
permalink: /:title # Post permalink
timezone: America/Fortaleza # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax: true # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
sass:
  style: :compressed

# Other Params
include: ["robots.txt"]
exclude: ["LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script"]
plugins:
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      layout: "null"
  - scope:
      type: "pages"
    values:
      layout: "page"
  - scope:
      type: "posts"
    values:
      layout: "post"

jekyll_admin:
  homepage: "pages"
